//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADayInTheLifeAPI.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADayInTheLifeEntities : DbContext
    {
        public ADayInTheLifeEntities()
            : base("name=ADayInTheLifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Avatar> Avatars { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<Education> Educations { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemType> ItemTypes { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<PlayerInGame> PlayerInGames { get; set; }
        public DbSet<Turn> Turns { get; set; }
        public DbSet<SocietyType> SocietyTypes { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<PlayerSystem> PlayerSystems { get; set; }
        public DbSet<TurnMove> TurnMoves { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
    }
}
