//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADayInTheLifeAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string Name { get; set; }
        public int BaseRate { get; set; }
        public int EducationId { get; set; }
        public int HoursWorked { get; set; }
    }
}
