//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADayInTheLifeAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInGame
    {
        public int PlayerInGameId { get; set; }
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public bool Accepted { get; set; }
        public int PlayerPosition { get; set; }
    }
}
